# Generated by Django 5.2.1 on 2025-05-26 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Paydaş Adı')),
                ('stakeholder_type', models.CharField(choices=[('department', 'Belediye Birimi'), ('company', 'Firma/Şirket'), ('institution', 'Kurum'), ('ngo', 'STK'), ('other', 'Diğer')], max_length=20, verbose_name='Paydaş Türü')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='İlgili Kişi')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='İletişim E-posta')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='İletişim Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('website', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stakeholders/logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Paydaş',
                'verbose_name_plural': 'Paydaşlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Proje Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Kısaltması')),
                ('description', models.TextField(verbose_name='Proje Açıklaması')),
                ('short_description', models.TextField(max_length=500, verbose_name='Kısa Açıklama')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='Planlanan Bitiş Tarihi')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Gerçekleşen Bitiş Tarihi')),
                ('status', models.CharField(choices=[('planning', 'Planlama Aşamasında'), ('development', 'Geliştirme Aşamasında'), ('testing', 'Test Aşamasında'), ('implementation', 'Uygulama Aşamasında'), ('live', 'Canlıda'), ('completed', 'Tamamlandı'), ('suspended', 'Askıya Alındı'), ('cancelled', 'İptal Edildi')], default='planning', max_length=20, verbose_name='Durum')),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, help_text='0-100 arası değer', verbose_name='İlerleme Yüzdesi')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/featured/', verbose_name='Kapak Görseli')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Bütçe (TL)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan Proje')),
                ('is_public', models.BooleanField(default=True, verbose_name='Halka Açık')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cms.projectcategory', verbose_name='Kategori')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Proje Yöneticisi')),
                ('stakeholders', models.ManyToManyField(blank=True, to='projects.stakeholder', verbose_name='Paydaşlar')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ödül Adı')),
                ('organization', models.CharField(max_length=200, verbose_name='Veren Kuruluş')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('award_date', models.DateField(verbose_name='Ödül Tarihi')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='projects/awards/', verbose_name='Sertifika/Belge')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/awards/images/', verbose_name='Ödül Görseli')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='projects.project', verbose_name='Proje')),
            ],
            options={
                'verbose_name': 'Ödül',
                'verbose_name_plural': 'Ödüller',
                'ordering': ['-award_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('progress_percentage', models.PositiveSmallIntegerField(help_text='0-100 arası değer', verbose_name='İlerleme Yüzdesi')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='projects/progress/attachments/', verbose_name='Dosya Eki')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/progress/images/', verbose_name='Görsel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_records', to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='projects.project', verbose_name='Proje')),
            ],
            options={
                'verbose_name': 'İlerleme Kaydı',
                'verbose_name_plural': 'İlerleme Kayıtları',
                'ordering': ['-date'],
            },
        ),
    ]
