services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app
    command: gunicorn akillisehir.wsgi:application --bind 0.0.0.0:8000 --workers 2
