# Generated by Django 5.2.1 on 2025-05-26 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(default='fas fa-folder', max_length=50, verbose_name='Font Awesome İkon')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='Renk')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Proje Kategorisi',
                'verbose_name_plural': 'Proje Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('title', models.CharField(max_length=200, verbose_name='Proje Başlığı')),
                ('description', models.TextField(verbose_name='Proje Açıklaması')),
                ('expected_benefit', models.TextField(verbose_name='Beklenen Fayda')),
                ('estimated_cost', models.CharField(blank=True, max_length=100, verbose_name='Tahmini Maliyet')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('viewed', 'Görüldü'), ('under_review', 'İnceleme Altında'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('archived', 'Arşivlendi')], default='pending', max_length=20, verbose_name='Durum')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Görülme Tarihi')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Arşivlenme Tarihi')),
                ('archive_reason', models.TextField(blank=True, verbose_name='Arşivleme Sebebi')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Arşivleyen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.projectcategory', verbose_name='Kategori')),
                ('viewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Görüleyen')),
            ],
            options={
                'verbose_name': 'Proje Önerisi',
                'verbose_name_plural': 'Proje Önerileri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('last_submission', models.DateTimeField(auto_now=True, verbose_name='Son Gönderim')),
                ('submission_count', models.PositiveIntegerField(default=1, verbose_name='Gönderim Sayısı')),
            ],
            options={
                'verbose_name': 'Hız Sınırlama',
                'verbose_name_plural': 'Hız Sınırlamaları',
                'unique_together': {('ip_address', 'email')},
            },
        ),
    ]
