# Generated by Django 5.2.1 on 2025-05-26 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Kategori Kodu'),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('organization', models.CharField(blank=True, max_length=150, verbose_name='Kurum/Şirket')),
                ('subject', models.CharField(choices=[('general', 'Genel Bilgi'), ('suggestion', 'Öneri'), ('complaint', 'Şikayet'), ('technical', 'Teknik Destek'), ('project', 'Proje Hakkında'), ('cooperation', 'İş Birliği'), ('other', 'Diğer')], default='general', max_length=20, verbose_name='Konu')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=20, verbose_name='Öncelik')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('read', 'Okundu'), ('in_progress', 'İşlemde'), ('replied', 'Yanıtlandı'), ('resolved', 'Çözüldü'), ('closed', 'Kapatıldı')], default='new', max_length=20, verbose_name='Durum')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Tarihi')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Yönetici Notları')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Yönetici')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='Okuyan Yönetici')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='cms_contact_status_34aaa4_idx'), models.Index(fields=['subject', '-created_at'], name='cms_contact_subject_09d893_idx'), models.Index(fields=['priority', '-created_at'], name='cms_contact_priorit_d8c8a2_idx')],
            },
        ),
    ]
