# Generated by Django 5.2.1 on 2025-05-27 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_projectcategory_slug_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonelStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Cep Telefonu')),
                ('department', models.CharField(choices=[('akilli_sehir', 'Akıllı Şehir Müdürlüğü'), ('cbs', 'CBS (Coğrafi Bilgi Sistemi)'), ('it_support', 'IT Destek'), ('project_management', 'Proje Yönetimi'), ('data_analysis', 'Veri Analizi'), ('network', 'Ağ Yönetimi'), ('software_dev', 'Yazılım Geliştirme'), ('quality_assurance', 'Kalite Güvence'), ('coordination', 'Koordinasyon'), ('other', 'Diğer')], default='akilli_sehir', max_length=50, verbose_name='Departman')),
                ('position', models.CharField(choices=[('director', 'Müdür'), ('deputy_director', 'Müdür Yardımcısı'), ('chief', 'Şef'), ('senior_specialist', 'Kıdemli Uzman'), ('specialist', 'Uzman'), ('engineer', 'Mühendis'), ('senior_developer', 'Kıdemli Geliştirici'), ('developer', 'Yazılım Geliştirici'), ('analyst', 'Sistem Analisti'), ('technician', 'Teknisyen'), ('coordinator', 'Koordinatör'), ('assistant', 'Asistan'), ('secretary', 'Kalem'), ('intern', 'Stajyer')], max_length=50, verbose_name='Pozisyon')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Personel No')),
                ('office_location', models.CharField(blank=True, max_length=100, verbose_name='Ofis Konumu')),
                ('office_phone', models.CharField(blank=True, max_length=20, verbose_name='Ofis Telefonu')),
                ('extension', models.CharField(blank=True, max_length=10, verbose_name='Dahili')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='staff/profiles/', verbose_name='Profil Fotoğrafı')),
                ('bio', models.TextField(blank=True, verbose_name='Kısa Biyografi')),
                ('specialties', models.TextField(blank=True, help_text='Virgülle ayırarak yazın (örn: Python, Django, PostgreSQL)', verbose_name='Uzmanlık Alanları')),
                ('education', models.TextField(blank=True, verbose_name='Eğitim Bilgileri')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Profili')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub Profili')),
                ('website_url', models.URLField(blank=True, verbose_name='Kişisel Website')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Pasif'), ('on_leave', 'İzinli'), ('transferred', 'Nakil'), ('retired', 'Emekli')], default='active', max_length=20, verbose_name='Durum')),
                ('hire_date', models.DateField(verbose_name='İşe Başlama Tarihi')),
                ('is_public', models.BooleanField(default=True, help_text='Bu personelin bilgileri web sitesinde gösterilsin mi?', verbose_name='Halka Açık')),
                ('is_manager', models.BooleanField(default=False, help_text='Bu personel bir takım/departman yöneticisi mi?', verbose_name='Yönetici')),
                ('can_approve_projects', models.BooleanField(default=False, verbose_name='Proje Onay Yetkisi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
                'ordering': ['department', 'position', 'last_name', 'first_name'],
                'indexes': [models.Index(fields=['department', 'status'], name='cms_persone_departm_b47480_idx'), models.Index(fields=['position', 'status'], name='cms_persone_positio_ed983b_idx'), models.Index(fields=['employee_id'], name='cms_persone_employe_0fe6c7_idx')],
            },
        ),
    ]
