# Generated by Django 5.2.1 on 2025-06-03 07:31

import django.db.models.deletion
import fileman.models
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DosyaTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Dosya Tipi Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(default='fas fa-file', max_length=50, verbose_name='Font Awesome İkon')),
                ('color', models.CharField(default='#138D19', max_length=20, verbose_name='Renk')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Dosya Tipi',
                'verbose_name_plural': 'Dosya Tipleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DosyaKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Kategori UUID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(default='fas fa-folder', max_length=50, verbose_name='Font Awesome İkon')),
                ('color', models.CharField(default='#138D19', max_length=20, verbose_name='Renk')),
                ('slug', models.SlugField(help_text="Kategori URL'si için benzersiz bir slug oluşturun.", max_length=100, unique=True, verbose_name='Kategori Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fileman.dosyakategori', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Dosya Kategorisi',
                'verbose_name_plural': 'Dosya Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('file', models.FileField(upload_to=fileman.models.dosya_upload_path, verbose_name='Dosya')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='fileman.dosyakategori', verbose_name='Kategori')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='fileman.dosyatip', verbose_name='Dosya Tipi')),
            ],
            options={
                'verbose_name': 'Dosya',
                'verbose_name_plural': 'Dosyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
